modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/architectury/architectury-extras/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "architectury_extras"
version = "${version}"
displayName = "Architectury Extras"
authors = "shedaniel"
description = '''
Extra APIs for Architectury.
'''
logoFile = "icon.png"
license = "LGPL-3"

[[dependencies.architectury_extras]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_extras]]
modId = "forge"
mandatory = true
versionRange = "[38.0.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_extras]]
modId = "architectury"
mandatory = true
versionRange = "[4.0,)"
ordering = "NONE"
side = "BOTH"
