modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "storagenetwork"
version = "${version}"
displayName = "Simple Storage Network"
authors = "shedaniel, Lothrazar, MrRiegel"
description = '''
Storage Network to connect inventories to search and craft
'''
license = "MIT"